version: '3.3'

services:
  app:
    image: fireflyiii/core:latest
    volumes:
      - firefly_iii_upload:/var/www/firefly-iii/storage/upload
    env_file: .env
    ports:
      - 8513:8080
    depends_on:
      - db
  db:
    image: mariadb
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=firefly
      - MYSQL_PASSWORD=secret_firefly_password
      - MYSQL_DATABASE=firefly
    volumes:
      - firefly_iii_db:/var/lib/mysql-docker
volumes:
   firefly_iii_upload:
   firefly_iii_db:
